version: '2.2'

services:
  redis:
    image: redis
    restart: always
    command: redis-server --requirepass mars7x3
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/usr/local/etc/redis
    networks:
      - mars7x3-redis

  web:
    build: ./
    container_name: web_container
    restart: always
    command: bash entrypoint.sh
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    networks:
      - mars7x3-redis


networks:
  mars7x3-redis:
    driver: bridge

volumes:
  static_volume:
  media_volume:
  redis_data:
